spring.application.name=gestion-viajes

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_viajes
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
